version: '3.8'
services:
  webapp:
    build: .
    container_name: webapp_dev
    ports:
      - "5000:5000"
    networks:
      - devops-net

networks:
  devops-net:
    external: true
    name: devops-net